'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QFIL_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;data&gt;
        '''  &lt;erase physical_partition_number=&quot;#&quot; start_sector=&quot;@&quot; num_partition_sectors=&quot;$&quot; SECTOR_SIZE_IN_BYTES=&quot;4096&quot; /&gt;
        '''&lt;/data&gt;.
        '''</summary>
        Friend ReadOnly Property erase_xml() As String
            Get
                Return ResourceManager.GetString("erase_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fh_loader() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fh_loader", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property licence() As String
            Get
                Return ResourceManager.GetString("licence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ftm
        '''modemst1
        '''modemst2
        '''fsg
        '''fsc
        '''#
        '''abl_a
        '''abl_b
        '''boot_a
        '''boot_b
        '''laf_a
        '''laf_b
        '''xbl_a
        '''xbl_config_a
        '''xbl_b
        '''xbl_config_b
        '''#
        '''system_a
        '''product_a
        '''vendor_a
        '''OP_a
        '''modem_a
        '''# 
        '''system_b
        '''product_b
        '''vendor_b
        '''OP_b
        '''modem_b
        '''#
        '''ftm
        '''modem_a
        '''modem_b
        '''sid_a
        '''sid_b
        '''OP_a
        '''OP_b
        '''#
        '''lun1
        '''lun2
        '''lun3
        '''lun5
        '''lun6
        '''#
        '''lun0
        '''#
        '''lun4.
        '''</summary>
        Friend ReadOnly Property list_vital() As String
            Get
                Return ResourceManager.GetString("list_vital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	@-Full backup (LUN mode)
        '''	@-Full backup (partitions)
        '''	@-Quick backup (LUNs)
        '''	@-Quick backup (Partitions)
        '''	@-Userdata backup
        '''	@-Selective erase
        '''	@-Detect connected COM ports
        '''	@-Flash files (from Flash folder)
        '''	Q-Quit
        '''	#
        '''	@-Full backup (LUN mode)
        '''	@-Full backup (partitions)
        '''	@-Userdata backup
        '''	@-Detect connected COM ports
        '''	@-Flash files (from Flash folder)
        '''	Q-Quit
        '''	#
        '''	@-Backup: ABL, Boot, LAF, XBL
        '''	@-Backup: FTM, Modemst, FSG, FSC
        '''	@-Backup: System, Product, Vendor, OP, Modem [A]
        '''	@-Backu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property menu_en() As String
            Get
                Return ResourceManager.GetString("menu_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	@-Полный бэкап (режим LUN)
        '''	@-Полный бэкап (разделы)
        '''	@-Быстрый бэкап (LUN-ны)
        '''	@-Быстрый бэкап (разделы)
        '''	@-Сохранить userdata
        '''	@-Выборочное удаление
        '''	@-Проверка подключенных портов
        '''	@-Прошить файлы (из директории Flash)
        '''	Q-Выход
        '''	#
        '''	@-Полный бэкап (режим LUN)
        '''	@-Полный бэкап (разделы)
        '''	@-Сохранить userdata
        '''	@-Проверка подключенных портов
        '''	@-Прошить файлы (из директории Flash)
        '''	Q-Выход
        '''	#
        '''	@-Сохранить: ABL, Boot, LAF, XBL
        '''	@-Сохранить: FTM, Modemst, FSG, FSC
        '''	@-Сохранить: System, Produc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property menu_ru() As String
            Get
                Return ResourceManager.GetString("menu_ru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available
        ''' QFIL Helper v@: GPT Editon | Advanced mode: On
        ''' QFIL Helper v@: GPT Editon | Advanced mode: Off
        '''Available
        '''Error: Failed to apply NTFS compression to the backup folder! Aborting...
        '''WARNING: You&apos;re about to backup the USERDATA partiton!
        '''This process uses NTFS compression and requires a powerful PC and fast USB port!!!
        '''Due to the size of userdata partiton this process can last very long time!!!
        '''Are you absolutly sure you want to procceed?! (Y|N)
        '''S-Skip | A-Abort
        '''Error: fh_loader is unable  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property msg_en() As String
            Get
                Return ResourceManager.GetString("msg_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available
        ''' QFIL Helper v@: GPT Editon | Расширенный режим: Вкл
        ''' QFIL Helper v@: GPT Editon | Расширенный режим: Откл
        '''Available
        '''Ошибка: Не удалось применить NTFS сжатие к папке бэкапа! Отменяю сохранение...
        '''ВНИМАНИЕ: Вы собираетесь сохранить раздел USERDATA!
        '''Этот процесс использует NTFS сжатие и требует мощный ПК и быстрый USB порт!!!
        '''Ввиду размера раздела userdata, процесс может занять длительное время!!!
        '''Вы абсолютно уверенны что хотите продолжить?! (Y|N)
        '''S-Пропустить | A-Отменить
        '''Ошибка: fh_load [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property msg_ru() As String
            Get
                Return ResourceManager.GetString("msg_ru", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
