'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QFIL_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to abl_a
        '''abl_b
        '''boot_a
        '''boot_b
        '''laf_a
        '''laf_b
        '''xbl_a
        '''xbl_config_a
        '''xbl_b
        '''xbl_config_b.
        '''</summary>
        Friend ReadOnly Property boot_partitons() As String
            Get
                Return ResourceManager.GetString("boot_partitons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to What would you like to do?
        '''	1-Backup partitions
        '''	2-Backup hidden partitions
        '''	3-Backup LUNs
        '''	4-Backup hidden LUNs (manual)
        '''	Q-Quit
        '''Invalid input, please try again...
        '''Something went wrong! Unable to parse the line: 
        '''Something went wrong! Unable to calculate size of LUN: 
        '''Saving: 
        '''Error: fh_loader is unable to communicate to the COM Port!
        '''	Things to check:
        '''	1. Have you connected your phone to the PC?
        '''	2. Have you put your phone in the EDL mode?
        '''	3. Have you run QFIL and loaded the partition manag [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property english() As String
            Get
                Return ResourceManager.GetString("english", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fh_loader() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fh_loader", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property licence() As String
            Get
                Return ResourceManager.GetString("licence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Выберете задачу:
        '''	1-Сохранить разделы
        '''	2-Сохранить скрытые разделы
        '''	3-Сохранить диски (LUN)
        '''	4-Сохранить скрытые диски (вручную)
        '''	Q-Выход
        '''Неверный ввод, попробуйте еще раз...
        '''Что-то пошло не так! Не могу выполнить парсинг этой строчки: 
        '''Что-то пошло не так! Не могу вычислить размеры логического диска: 
        '''Сохраняю: 
        '''Ошибка: fh_loader не может связаться с COM-портом!
        '''	Проверьте и убедитесь что:
        '''	1. Ваш телефон подключен к компьютеру
        '''	2. Телефон находится в режиме EDL
        '''	3. Программа QFIL запущенна и [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property russian() As String
            Get
                Return ResourceManager.GetString("russian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ftm
        '''modemst1
        '''modemst2
        '''fsg
        '''fsc.
        '''</summary>
        Friend ReadOnly Property vital_partitions() As String
            Get
                Return ResourceManager.GetString("vital_partitions", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
