'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QFIL_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fh_loader() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fh_loader", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property licence() As String
            Get
                Return ResourceManager.GetString("licence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to abl_a
        '''abl_b
        '''boot_a
        '''boot_b
        '''laf_a
        '''laf_b
        '''xbl_a
        '''xbl_config_a
        '''xbl_b
        '''xbl_config_b.
        '''</summary>
        Friend ReadOnly Property list_boot() As String
            Get
                Return ResourceManager.GetString("list_boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ftm
        '''modemst1
        '''modemst2
        '''fsg
        '''fsc.
        '''</summary>
        Friend ReadOnly Property list_vital() As String
            Get
                Return ResourceManager.GetString("list_vital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	@-Backup partitions
        '''	@-Backup LUNs
        '''	@-Backup hidden partitions
        '''	@-Backup hidden LUNs (manual)
        '''	@-Backup: ABL, Boot, LAF, XBL
        '''	@-Backup: FTM, Modemst, FSG, FSC
        '''	@-Detect connected COM ports
        '''	@-Flash files (from Flash folder)
        '''	Q-Quit
        '''	# 
        '''	@-Backup partitions
        '''	@-Backup LUNs
        '''	@-Backup: ABL, Boot, LAF, XBL
        '''	@-Backup: FTM, Modemst, FSG, FSC
        '''	@-Detect connected COM ports
        '''	@-Flash files (from Flash folder)
        '''	Q-Quit.
        '''</summary>
        Friend ReadOnly Property menu_en() As String
            Get
                Return ResourceManager.GetString("menu_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	@-Сохранить разделы
        '''	@-Сохранить диски (LUN)
        '''	@-Сохранить скрытые разделы
        '''	@-Сохранить скрытые диски (вручную)
        '''	@-Сохранить разделы: ABL, Boot, LAX, XBL
        '''	@-Сохранить разделы: FTM, Modemst, FSG, FSC
        '''	@-Проверка подключенных портов
        '''	@-Прошить файлы (из директории Flash)
        '''	Q-Выход
        '''	#
        '''	@-Сохранить разделы
        '''	@-Сохранить диски (LUN)
        '''	@-Сохранить разделы: ABL, Boot, LAX, XBL
        '''	@-Сохранить разделы: FTM, Modemst, FSG, FSC
        '''	@-Проверка подключенных портов
        '''	@-Прошить файлы (из директории Flash)
        '''	Q-Выход.
        '''</summary>
        Friend ReadOnly Property menu_ru() As String
            Get
                Return ResourceManager.GetString("menu_ru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QFIL Helper v@
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''Error: fh_loader is unable to communicate to the COM Port!
        '''	Things to check:
        '''	1. Have you connected your phone to the PC?
        '''	2. Have you put your phone in the EDL mode?
        '''	3. Have you run QFIL and loaded the partition manager window?
        '''	4. Have saved new COMx_PartitionsList.xml in the QFIL folder?
        '''Press any key to return to the main menu
        '''Error: Unable to locate fh_loader.exe
        '''Error: Unable to locate COMx_PartitionsList.xml
        '''Error: Unable to extract COM Port number from the [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property msg_en() As String
            Get
                Return ResourceManager.GetString("msg_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QFIL Helper v@
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''Ошибка: fh_loader не может связаться с COM-портом!
        '''	Проверьте и убедитесь что:
        '''	1. Ваш телефон подключен к компьютеру
        '''	2. Телефон находится в режиме EDL
        '''	3. Программа QFIL запущенна и окно менеджера разделов открыто
        '''	4. Вы сохранили новый COMx_PartitionsList.xml в папку QFIL
        '''Нажмите любую клавишу для возврата в главное меню
        '''Ошибка: Не удалось найти fh_loader.exe
        '''Ошибка: Не удалось найти COMx_PartitionsList.xml
        '''Нажмите любую клавишу для продолжения...
        '''Ошибка: Не уд [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property msg_ru() As String
            Get
                Return ResourceManager.GetString("msg_ru", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
