What would you like to do?
	1-Backup partitions
	2-Backup hidden partitions
	3-Backup LUNs
	4-Backup hidden LUNs (manual)
	Q-Quit
Invalid input, please try again...
Something went wrong! Unable to parse the line: 
Something went wrong! Unable to calculate size of LUN: 
Saving: 
Error: fh_loader is unable to communicate to the COM Port!
	Things to check:
	1. Have you connected your phone to the PC?
	2. Have you put your phone in the EDL mode?
	3. Have you run QFIL and loaded the partition manager window?
	4. Have saved new COMx_PartitionsList.xml in the QFIL Helper folder?
Press any key to return to the main menu
Error: Unable to locate fh_loader.exe
Error: Unable to locate COMx_PartitionsList.xml
Error: Unable to extract COM Port number from the COMx_PartitionsList.xml
Press any key to quit...
Enter LUN index (3,6?) | Q-Main menu
Enter number of sectors (@?) | Q-Main menu
Saving LUN: 